<html>
<head><title><?php echo $this->name ?></title>
  <script type="text/javascript" src="/lib/<?php echo $this->dojo_base_dir ?>/dojo/dojo.js"<?php
  if (isset($this->dj_config) && strlen($this->dj_config) > 0) echo 'djConfig="' . $this->dj_config . '"'?>></script>
<?php
if (isset($this->layers) && strlen($this->layers) > 0) {
  $layersAr = preg_split('/##/', $this->layers);
  foreach ($layersAr as $layerName) {
    // @TODO: improve our knowledge of 'layers', as some have dependencies.
    // dijit-all.js has a layerDependency on dijit/dijit.js
    if (strpos($layerName, 'dijit-all.js') > 0) {
      echo '  <!-- auto-inserted dijit.js dependency to satisfy dijit-all.js -->' . "\n" .
        '  <script type="text/javascript" ' .
        'src="/lib/' . $this->dojo_base_dir . '/dijit/dijit.js"></script>' . "\n";
    }
    echo '  <script type="text/javascript" ' .
      'src="/lib/' . $this->dojo_base_dir . '/' . $layerName . '"></script>' . "\n";
  }
}
?>

  <link rel="stylesheet" href="/lib/<?php echo $this->dojo_base_dir ?>/dojo/resources/dojo.css">
  <link rel="stylesheet" href="/lib/<?php echo $this->dojo_base_dir ?>/dijit/themes/<?php echo $this->dojo_theme ?>/<?php echo $this->dojo_theme ?>.css">

<?php if (isset($this->javascript) && strlen($this->javascript) > 0) { ?>
  <script type="text/javascript">
<?php echo $this->javascript . "\n";?>
  </script>
<?php }
if (isset($this->css) && strlen($this->css) > 0) { ?>
  <style type="text/css">
<?php echo $this->css . "\n"; ?>
  </style>
<?php } ?></head>
<body class="<?php echo $this->dojo_theme ?>">
<?php 
	echo $this->html;
?>
</body>
</html>